import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import MainView from 'src/views/MainView';

const Home: NextPage = () => {
	return (
		<div className='px-8'>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<MainView />

			<footer className='py-8 flex justify-center items-center border-t border-t-gray-300'>
				<a
					className='flex-grow flex justify-center items-center'
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className='ml-2 h-4'>
						<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
};

export default Home;
